### ISSUE TITLE
mkvirtualenv command issue

### ISSUE THREAD

**Issue by nathankurt** [SpartaHack/SpartaHack_API_2019#12]
When I try to use the `mkvirtualenv` command, it doesn't work and just lists out all of the possible options, Is there a destination we are supposed to put? I didn't see anything in the readme that shows something.

**Comment by yash1337** [comment]
Can you post a screenshot of it? Also, did you put the three lines in your .bashrc?

**Comment by nathankurt** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/9864281/42106821-5a4fd2a2-7ba3-11e8-82f0-35d19fb24dee.png">

Here is the screenshot, I think you just need to add the directory after it? I'm just not sure what directory we should put.

**Comment by yash1337** [comment]
No no. You need to tell it the name of the virtualenv. `mkvirtualenv virtualenv_name` then it will create the virtualenv at the destination you selected (the destination is in one of the three lines you need to put in .bashrc)

**Comment by yash1337** [comment]
I will update the readme explaining this.

**Comment by nathankurt** [comment]
oh gotcha, yeah just add on to the PR I made in that branch

**Comment by yash1337** [comment]
Sounds good!
