### ISSUE TITLE
Master or Develop branch seems to be behind one commit with no changes to show

### ISSUE THREAD

**Issue by yash1337** [SpartaHack/SpartaHack_API_2019#21]
This is a weird bug that I have not seen before and is driving me crazy. Someone needs to fix it.
I have tried creating a PR for master and when I merge it git tell me develop is behind one commit and the circle goes on.

**Comment by nathankurt** [comment]
I think I fixed it and it's merged.

**Comment by nathankurt** [comment]
oh wait, I see what you mean I think. I'll look into it.

**Comment by yash1337** [comment]
Cool thanks.

**Comment by nathankurt** [comment]
So I think that's not a really fixable issue since they shouldn't ever really be in complete sync. Since the merge counts as a commit that's what you're seeing there. I'm not sure there is much you can do to fix it. closing
