### ISSUE TITLE
Possible use of black? 

### ISSUE THREAD

**Issue by nathankurt** [SpartaHack/SpartaHack_API_2019#40]
Have we thought about using [black](https://github.com/ambv/black) as an auto formatter? I've looked into it a little bit, but it seems pretty cool so far!

**Comment by yash1337** [comment]
It only works for Python 3.6 and it's in beta stage currently.

**Comment by yash1337** [comment]
And code factor does exactly this.

**Comment by nathankurt** [comment]
Yeah that's true, I found this before i found code factor. Closing issue since not needed.
